export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FALIURE = "VERIFY_FALIURE";
export const SURVAY_ANALYSIS_SUCCESS = "SURVAY_ANALYSIS_SUCCESS";
export const SURVAY_ANALYSIS_FALIURE = "SURVAY_ANALYSIS_FALIURE";
